import {
  Bath,
  BedDouble,
  BookOpen,
  Building2,
  CalendarCheck,
  ChevronDown,
  Car,
  CheckCircle2,
  Clock,
  CookingPot,
  DoorOpen,
  Dumbbell,
  Droplets,
  Flame,
  Home,
  Image as ImageIcon,
  Landmark,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Monitor,
  Navigation,
  ParkingCircle,
  Phone,
  Plane,
  Presentation,
  ReceiptText,
  Salad,
  ShieldCheck,
  Shirt,
  Snowflake,
  Sparkles,
  Star,
  Utensils,
  Users,
  WashingMachine,
  Wifi,
  X,
  type LucideIcon
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  Bath,
  BedDouble,
  BookOpen,
  Building2,
  CalendarCheck,
  ChevronDown,
  Car,
  CheckCircle2,
  Clock,
  CookingPot,
  DoorOpen,
  Dumbbell,
  Droplets,
  Flame,
  Home,
  ImageIcon,
  Landmark,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Monitor,
  Navigation,
  ParkingCircle,
  Phone,
  Plane,
  Presentation,
  ReceiptText,
  Salad,
  ShieldCheck,
  Shirt,
  Snowflake,
  Sparkles,
  Star,
  Utensils,
  Users,
  WashingMachine,
  Wifi,
  X
};

export function Icon({ name, className, "aria-hidden": ariaHidden = true }: { name: string; className?: string; "aria-hidden"?: boolean }) {
  const Component = icons[name] ?? CheckCircle2;
  return <Component aria-hidden={ariaHidden} className={className} />;
}
